"use client";
import { useRef, useState } from "react";
import { makeFamily, makeMatchSet, makeMemoryPairs, makeQuestion } from "@/lib/math-engine";
import { recordAnswer } from "@/lib/learning-engine";
import { Progress } from "@/lib/storage";
import { tone } from "@/lib/sound";
import { QuestionCard } from "./QuizModes";
export type Game = "balloon"|"memory"|"rocket"|"tower"|"pairs";

export function Family({sound}:{sound:boolean}){const [f,setF]=useState(()=>makeFamily()),[sel,setSel]=useState<string[]>([]),[check,setCheck]=useState(false);const ok=sel.length===4&&sel.every(x=>f.correct.includes(x));return <div className="card mx-auto max-w-3xl p-6 md:p-8"><div className="text-center"><div className="text-5xl">👨‍👩‍👧‍👦</div><h2 className="mt-3 text-3xl font-black">Семья примеров</h2><p className="mt-2 text-slate-500">Выбери четыре верных равенства из трёх чисел.</p><div className="mt-5 flex justify-center gap-3">{[f.a,f.b,f.p].map(n=><span key={n} className="grid h-20 w-20 place-items-center rounded-3xl bg-violet-100 text-3xl font-black text-violet-700">{n}</span>)}</div></div><div className="mt-7 grid gap-3 sm:grid-cols-2">{f.options.map(o=><button key={o} onClick={()=>!check&&setSel(s=>s.includes(o)?s.filter(x=>x!==o):s.length<4?[...s,o]:s)} className={`answer ${sel.includes(o)?"!border-violet-500 !bg-violet-50":""}`}>{o}</button>)}</div>{check&&<div className={`mt-5 rounded-2xl p-4 text-center font-black ${ok?"bg-emerald-50 text-emerald-700":"bg-orange-50 text-orange-800"}`}>{ok?"🎉 Всё верно!":"Проверь: умножение и деление должны связывать те же три числа."}</div>}<div className="mt-5 grid grid-cols-2 gap-3"><button onClick={()=>{setCheck(true);tone(ok?"ok":"bad",sound)}} className="answer !bg-violet-600 !text-white">Проверить</button><button onClick={()=>{setF(makeFamily());setSel([]);setCheck(false)}} className="answer">Новая семья</button></div></div>}

export function Games({game,setGame,p,setP}:{game:Game|null;setGame:(g:Game|null)=>void;p:Progress;setP:(p:Progress)=>void}){
  if(!game){const gs:[Game,string,string][]=[["balloon","🎈","Лопни шарик"],["memory","🧠","Память"],["pairs","🔗","Найди пару"],["rocket","🚀","Ракета"],["tower","🏗️","Построй башню"]];return <><h1 className="mb-5 text-3xl font-black">Учимся в движении 🎮</h1><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{gs.map(([g,i,t])=><button key={g} onClick={()=>setGame(g)} className="card press p-6 text-left"><div className="text-5xl">{i}</div><h2 className="mt-3 text-2xl font-black">{t}</h2></button>)}</div></>}
  if(game==="balloon")return <Balloon p={p} setP={setP}/>; if(game==="memory")return <Memory sound={p.sound}/>; if(game==="pairs")return <Pairs sound={p.sound}/>;return <Build type={game} p={p} setP={setP}/>;
}
function Balloon({p,setP}:{p:Progress;setP:(p:Progress)=>void}){const [q,setQ]=useState(()=>makeQuestion({kind:"choice"})),[score,setScore]=useState(0),[pop,setPop]=useState<number|null>(null);const start=useRef(Date.now());const hit=(n:number)=>{if(pop!==null)return;const ok=n===q.answer;if(ok)setPop(n);setP(recordAnswer(p,q,ok,Date.now()-start.current));tone(ok?"ok":"bad",p.sound);if(ok){setScore(x=>x+1);setTimeout(()=>{setQ(makeQuestion({kind:"choice"}));setPop(null);start.current=Date.now()},400)}};return <div className="card mx-auto max-w-3xl p-6 text-center md:p-8"><div className="flex justify-between"><h2 className="text-2xl font-black">🎈 Лопни шарик</h2><b>⭐ {score}</b></div><div className="mt-7 text-5xl font-black">{q.prompt}</div><div className="mt-8 grid grid-cols-2 gap-5 sm:grid-cols-4">{q.choices!.map((n,i)=><button key={n} onClick={()=>hit(n)} className={`balloon mx-auto grid h-28 w-24 place-items-center rounded-[50%_50%_48%_48%] text-2xl font-black text-white shadow-xl ${["bg-pink-500","bg-cyan-500","bg-violet-500","bg-orange-500"][i]} ${pop===n?"scale-0 opacity-0 transition duration-300":""}`}>{n}</button>)}</div></div>}
function Memory({sound}:{sound:boolean}){const [cards,setCards]=useState(()=>makeMemoryPairs()),[open,setOpen]=useState<string[]>([]),[done,setDone]=useState<string[]>([]);const click=(id:string)=>{if(open.includes(id)||done.includes(id)||open.length===2)return;const n=[...open,id];setOpen(n);tone("tap",sound);if(n.length===2){const a=cards.find(c=>c.id===n[0])!,b=cards.find(c=>c.id===n[1])!;if(a.pair===b.pair){setDone(x=>[...x,a.id,b.id]);setOpen([]);tone("ok",sound)}else setTimeout(()=>setOpen([]),650)}};return <div className="card mx-auto max-w-2xl p-6"><h2 className="text-center text-2xl font-black">🧠 Память</h2><div className="mt-6 grid grid-cols-4 gap-3">{cards.map(c=>{const v=open.includes(c.id)||done.includes(c.id);return <button key={c.id} onClick={()=>click(c.id)} className={`aspect-square rounded-2xl text-lg font-black transition md:text-2xl ${done.includes(c.id)?"bg-emerald-100 text-emerald-700":v?"border-2 border-violet-300 bg-white":"bg-gradient-to-br from-violet-600 to-blue-500 text-white"}`}>{v?c.label:"?"}</button>})}</div>{done.length===cards.length&&<div className="mt-5 rounded-2xl bg-emerald-50 p-4 text-center font-black text-emerald-700">🎉 Все пары найдены!</div>}<button onClick={()=>{setCards(makeMemoryPairs());setOpen([]);setDone([])}} className="answer mt-5 w-full">Новая игра</button></div>}
function Pairs({sound}:{sound:boolean}){const [s,setS]=useState(()=>makeMatchSet()),[left,setLeft]=useState<string|null>(null),[done,setDone]=useState<string[]>([]),[shake,setShake]=useState(false);const ans=(a:number)=>{if(!left)return;const r=s.rows.find(x=>x.id===left)!;if(r.answer===a){setDone(x=>[...x,left]);setLeft(null);tone("ok",sound)}else{setShake(true);tone("bad",sound);setTimeout(()=>setShake(false),300)}};return <div className={`card mx-auto max-w-3xl p-6 ${shake?"shake":""}`}><h2 className="text-center text-2xl font-black">🔗 Найди пару</h2><p className="mt-2 text-center text-slate-500">Сначала нажми пример, потом его ответ.</p><div className="mt-6 grid grid-cols-2 gap-5"><div className="space-y-3">{s.rows.map(r=><button disabled={done.includes(r.id)} key={r.id} onClick={()=>setLeft(r.id)} className={`answer w-full ${left===r.id?"!border-violet-500 !bg-violet-50":""} disabled:opacity-25`}>{r.label}</button>)}</div><div className="space-y-3">{s.answers.map(a=><button key={a} onClick={()=>ans(a)} className="answer w-full">{a}</button>)}</div></div>{done.length===4&&<div className="mt-5 rounded-2xl bg-emerald-50 p-4 text-center font-black text-emerald-700">🎉 Все пары совпали!</div>}<button onClick={()=>{setS(makeMatchSet());setLeft(null);setDone([])}} className="answer mt-5 w-full">Новый набор</button></div>}
function Build({type,p,setP}:{type:"rocket"|"tower";p:Progress;setP:(p:Progress)=>void}){const [q,setQ]=useState(()=>makeQuestion({kind:"choice"})),[level,setLevel]=useState(0);const start=useRef(Date.now());const ans=(v:number|boolean)=>{const ok=v===q.answer;setP(recordAnswer(p,q,ok,Date.now()-start.current));tone(ok?"ok":"bad",p.sound);if(ok)setLevel(x=>Math.min(10,x+1));setTimeout(()=>{setQ(makeQuestion({kind:"choice"}));start.current=Date.now()},300)};if(level>=10)return <div className="card mx-auto max-w-xl p-8 text-center"><div className="text-7xl">{type==="rocket"?"🌕":"🏙️"}</div><h2 className="mt-4 text-3xl font-black">{type==="rocket"?"Ракета достигла Луны!":"Башня построена!"}</h2><p className="mt-2 text-slate-500">10 правильных ответов. Отличная работа!</p></div>;return <div className="grid gap-5 lg:grid-cols-[.65fr_1.35fr]"><div className="card grid min-h-80 place-items-center overflow-hidden p-5"><div className="relative h-64 w-full">{type==="rocket"?<><div className="absolute right-4 top-0 text-6xl">🌕</div><div className="absolute left-1/2 text-6xl transition-all duration-500" style={{bottom:`${level*8}%`,transform:"translateX(-50%)"}}>🚀</div></>:<div className="absolute bottom-0 left-1/2 flex -translate-x-1/2 flex-col-reverse items-center">{Array.from({length:level},(_,i)=><div key={i} className="h-6 border-2 border-white bg-gradient-to-r from-violet-500 to-blue-500 shadow" style={{width:`${160-i*6}px`}}/>)}<div className="text-5xl">🏗️</div></div>}</div><b>{level}/10</b></div><QuestionCard key={q.id} q={q} answer={ans} sound={p.sound}/></div>}
