"use client";
import { useEffect, useRef, useState } from "react";
import { TABLES, Question, makeQuestion } from "@/lib/math-engine";
import { hardFacts, nextAdaptiveQuestion, recordAnswer } from "@/lib/learning-engine";
import { Progress } from "@/lib/storage";
import { tone } from "@/lib/sound";

export function Train({p,setP,table,setTable}:{p:Progress;setP:(p:Progress)=>void;table?:number;setTable:(t?:number)=>void}){
  const [difficulty,setDifficulty]=useState<1|2|3|4|5|null>(null); if(difficulty===null)return <><Picker title="Что тренируем?" onPick={setTable}/><div className="card mx-auto mt-5 max-w-3xl p-5"><b>Сложность</b><div className="mt-3 grid grid-cols-5 gap-2">{[1,2,3,4,5].map(d=><button key={d} onClick={()=>setDifficulty(d as 1|2|3|4|5)} className="answer !p-3">{d}<small className="block text-[10px] text-slate-400">{["Легко","Норма","Сложно","Микс","Мастер"][d-1]}</small></button>)}</div></div></>;
  return <Quiz title={table?`🎯 Тренировка ×${table}`:"🎯 Смешанная тренировка"} count={15} p={p} setP={setP} table={table} adaptive division={difficulty>=4} hard={difficulty>=3}/>;
}
export function ModeWithTable({title,table,setTable,children}:{title:string;table?:number;setTable:(t?:number)=>void;children:React.ReactNode}){if(!table)return <Picker title={title} onPick={setTable}/>;return <>{children}</>}
export function Hard({p,setP}:{p:Progress;setP:(p:Progress)=>void}){const h=hardFacts(p);if(!h.length)return <div className="card mx-auto max-w-xl p-8 text-center"><div className="text-6xl">🌟</div><h2 className="mt-4 text-2xl font-black">Сложных примеров пока нет</h2><p className="mt-2 text-slate-500">Потренируйся — сюда попадут ошибки и примеры, над которыми ты долго думаешь.</p></div>;return <><div className="mb-4 rounded-3xl bg-orange-50 p-4 font-bold text-orange-800">🧠 Сейчас повторяем слабые места: {h.slice(0,8).map(([k])=>k.replace("m:","").replace(":"," × ")).join(", ")}</div><Quiz title="🧠 Мои сложные примеры" count={Math.min(15,Math.max(8,h.length*2))} p={p} setP={setP} adaptive hard/></>}
export function Test({p,setP}:{p:Progress;setP:(p:Progress)=>void}){const [n,setN]=useState<number|null>(null);if(!n)return <div className="card mx-auto max-w-2xl p-8 text-center"><div className="text-6xl">🏆</div><h2 className="mt-4 text-3xl font-black">Проверь себя</h2><p className="mt-2 text-slate-500">Смешанные примеры без подсказок и лишнего давления.</p><div className="mt-6 grid grid-cols-3 gap-3">{[10,20,30].map(x=><button key={x} onClick={()=>setN(x)} className="answer !text-2xl">{x}<small className="block text-xs text-slate-400">вопросов</small></button>)}</div></div>;return <Quiz title="🏆 Проверка знаний" count={n} p={p} setP={setP} division hard test/>}

export function Quiz({title,count,p,setP,table,adaptive,division,hard,force,test}:{title:string;count:number;p:Progress;setP:(p:Progress)=>void;table?:number;adaptive?:boolean;division?:boolean;hard?:boolean;force?:Question["kind"];test?:boolean}){
  const make=(base=p)=>force?makeQuestion({table,kind:force,allowDivision:true}):adaptive?nextAdaptiveQuestion(base,table,division):makeQuestion({table,allowDivision:division,harder:hard});
  const [q,setQ]=useState<Question>(()=>make()),[i,setI]=useState(0),[ok,setOk]=useState(0),[bad,setBad]=useState(0),[times,setTimes]=useState<number[]>([]),[done,setDone]=useState(false);const start=useRef(Date.now());
  const answer=(v:number|boolean)=>{const right=v===q.answer,ms=Date.now()-start.current,next=recordAnswer(p,q,right,ms);setP(next);right?setOk(x=>x+1):setBad(x=>x+1);setTimes(x=>[...x,ms]);tone(right?"ok":"bad",p.sound);setTimeout(()=>{if(i+1>=count){setDone(true);tone("done",p.sound)}else{setI(x=>x+1);setQ(make(next));start.current=Date.now()}},right?420:850)};
  if(done){const avg=times.length?times.reduce((a,b)=>a+b,0)/times.length/1000:0,score=Math.round(ok/count*100);return <div className="card mx-auto max-w-2xl p-8 text-center"><div className="text-6xl">{score>=90?"🏆":score>=70?"🎉":"💪"}</div><h2 className="mt-4 text-3xl font-black">{test?"Результат":"Отличная работа!"}</h2><div className="mt-6 grid grid-cols-3 gap-3"><Stat v={`${ok}/${count}`} l="правильно"/><Stat v={`${score}%`} l="точность"/><Stat v={`${avg.toFixed(1)} c`} l="среднее время"/></div><div className="mt-5 rounded-2xl bg-violet-50 p-4 font-black text-violet-700">+{ok} ⭐ · Ошибок: {bad}</div></div>}
  return <div className="mx-auto max-w-3xl"><div className="mb-4 flex items-center justify-between"><div><b className="text-violet-600">{title}</b><p className="text-sm font-bold text-slate-400">Вопрос {i+1} из {count}</p></div><span className="rounded-2xl bg-white px-4 py-2 font-black shadow-sm">🔥 {p.streak}</span></div><div className="mb-5 h-3 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-blue-500" style={{width:`${i/count*100}%`}}/></div><QuestionCard key={q.id} q={q} answer={answer} sound={p.sound}/></div>
}
export function QuestionCard({q,answer,sound}:{q:Question;answer:(v:number|boolean)=>void;sound:boolean}){
  const [input,setInput]=useState(""),[feedback,setFeedback]=useState<"ok"|"bad"|null>(null);const locked=feedback!==null;
  const submit=(v:number|boolean)=>{if(locked)return;const right=v===q.answer;setFeedback(right?"ok":"bad");answer(v)};
  const choice=q.choices&&["choice","word","division","missing"].includes(q.kind);
  return <div className={`card relative overflow-hidden p-6 md:p-9 ${feedback==="ok"?"correct-pop star-burst":feedback==="bad"?"shake":""}`}><div className="text-center"><small className="font-black uppercase tracking-[.18em] text-slate-400">{q.kind==="word"?"Задача из жизни":q.kind==="division"?"Деление":q.kind==="missing"?"Пропущенное число":q.kind==="truefalse"?"Верно или нет?":q.kind==="input"?"Введи ответ":"Выбери ответ"}</small><div className={`${q.kind==="word"?"mx-auto mt-5 max-w-xl text-2xl leading-snug":"mt-6 text-5xl md:text-7xl"} font-black`}>{q.prompt}</div></div>
    {choice&&<div className="mt-7 grid grid-cols-2 gap-3">{q.choices!.map(c=><button key={c} disabled={locked} onClick={()=>submit(c)} className="answer !text-2xl md:!text-3xl">{c}</button>)}</div>}
    {q.kind==="truefalse"&&<div className="mt-7 grid grid-cols-2 gap-3"><button disabled={locked} onClick={()=>submit(true)} className="answer !bg-emerald-50 !text-emerald-700">✅ Верно</button><button disabled={locked} onClick={()=>submit(false)} className="answer !bg-rose-50 !text-rose-700">❌ Неверно</button></div>}
    {q.kind==="input"&&<div className="mx-auto mt-7 max-w-sm"><div className="mb-3 min-h-20 rounded-2xl bg-slate-50 p-4 text-center text-4xl font-black text-violet-600">{input||"?"}</div><div className="grid grid-cols-3 gap-2">{[1,2,3,4,5,6,7,8,9].map(n=><button key={n} disabled={locked} onClick={()=>{tone("tap",sound);setInput(x=>(x+n).slice(0,3))}} className="answer !min-h-14 !p-2">{n}</button>)}<button onClick={()=>setInput(x=>x.slice(0,-1))} className="answer !min-h-14 !p-2">⌫</button><button onClick={()=>setInput(x=>(x+"0").slice(0,3))} className="answer !min-h-14 !p-2">0</button><button disabled={!input||locked} onClick={()=>submit(Number(input))} className="answer !min-h-14 !border-violet-600 !bg-violet-600 !p-2 !text-white">OK</button></div></div>}
    {feedback&&<div className={`mt-6 rounded-2xl p-4 text-center font-black ${feedback==="ok"?"bg-emerald-50 text-emerald-700":"bg-orange-50 text-orange-800"}`}>{feedback==="ok"?"🎉 Отлично!":<>Почти! <span className="block">{q.explanation}</span><small className="mt-1 block opacity-70">Этот пример ещё вернётся позже.</small></>}</div>}
  </div>
}

export function Speed({p,setP}:{p:Progress;setP:(p:Progress)=>void}){
  const [started,setStarted]=useState(false),[pause,setPause]=useState(false),[time,setTime]=useState(60),[q,setQ]=useState(()=>makeQuestion({kind:"choice"})),[right,setRight]=useState(0),[wrong,setWrong]=useState(0);const start=useRef(Date.now());
  useEffect(()=>{if(!started||pause||time<=0)return;const id=setInterval(()=>setTime(x=>x-1),1000);return()=>clearInterval(id)},[started,pause,time]);
  useEffect(()=>{if(time===0&&right>p.speedRecord)setP({...p,speedRecord:right})},[time]);
  if(!started)return <div className="card mx-auto max-w-xl p-8 text-center"><div className="text-6xl">⚡</div><h2 className="mt-3 text-3xl font-black">60 секунд</h2><p className="mt-2 text-slate-500">Сколько примеров успеешь решить? Это дополнительная игра, а не основной способ учиться.</p><b className="mt-4 block text-violet-600">Рекорд: {p.speedRecord}</b><button onClick={()=>setStarted(true)} className="press mt-5 w-full rounded-2xl bg-violet-600 p-4 font-black text-white">Старт!</button></div>;
  if(time<=0)return <div className="card mx-auto max-w-xl p-8 text-center"><div className="text-6xl">🏁</div><h2 className="mt-3 text-3xl font-black">Время!</h2><div className="mt-5 grid grid-cols-3 gap-3"><Stat v={`${right}`} l="правильно"/><Stat v={`${wrong}`} l="ошибок"/><Stat v={`${Math.max(p.speedRecord,right)}`} l="рекорд"/></div></div>;
  const ans=(v:number|boolean)=>{const ok=v===q.answer;setP(recordAnswer(p,q,ok,Date.now()-start.current));ok?setRight(x=>x+1):setWrong(x=>x+1);tone(ok?"ok":"bad",p.sound);setTimeout(()=>{setQ(makeQuestion({kind:"choice"}));start.current=Date.now()},220)};
  return <div className="mx-auto max-w-3xl"><div className="mb-4 flex justify-between"><b className="rounded-2xl bg-white px-5 py-3 shadow-sm">⏱️ {time} сек</b><button onClick={()=>setPause(x=>!x)} className="answer !min-h-0 !py-3">{pause?"▶️ Продолжить":"⏸️ Пауза"}</button></div>{pause?<div className="card p-12 text-center text-3xl font-black">Пауза ⏸️</div>:<QuestionCard key={q.id} q={q} answer={ans} sound={p.sound}/>}<p className="mt-4 text-center font-bold text-slate-500">✅ {right} · ❌ {wrong}</p></div>
}


function Stat({v,l}:{v:string;l:string}){return <div className="rounded-2xl bg-slate-50 p-3 text-center"><b className="text-xl md:text-2xl">{v}</b><small className="block uppercase tracking-wide text-slate-400">{l}</small></div>}
function Picker({title,onPick,all=true}:{title:string;onPick:(t?:number)=>void;all?:boolean}){return <div className="card mx-auto max-w-3xl p-6 text-center md:p-8"><div className="text-5xl">✖️</div><h2 className="mt-3 text-3xl font-black">{title}</h2><div className="mt-6 grid grid-cols-4 gap-3">{TABLES.map(t=><button key={t} onClick={()=>onPick(t)} className="answer !text-2xl">×{t}</button>)}</div>{all&&<button onClick={()=>onPick()} className="press mt-4 w-full rounded-2xl bg-violet-600 p-4 text-lg font-black text-white">🎲 Все таблицы вперемешку</button>}</div>}
